sonar.projectKey=Gerald-WM_CI-CD-MCM-WagnerMistlberger
sonar.organization=gerald-wm-dev

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,internal/store/postgres.go,internal/handler/postgres_handler.go,cmd/api/main.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.coverage.exclusions=internal/store/postgres.go,internal/handler/postgres_handler.go,cmd/api/main.go

sonar.go.coverage.reportPaths=coverage_filtered.out
sonar.sourceEncoding=UTF-8